name: Check TypeScript code

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "examples/**"
      - "debugger/**"
      - "tests/**"
      - "js-pkg/**"

jobs:
  check-ts-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check Formatting of Examples
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: examples/

    - name: Check Formatting of Debugger
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: debugger/

    - name: Check Formatting of Tests
      run: npx prettier --check "src/**/*.ts"
      working-directory: tests/

    - name: Check Formatting of React lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: js-pkg/react/

    - name: Check Formatting of SDK
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: js-pkg/sdk/

    - name: Check Formatting of client
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: js-pkg/client/

    - name: Check Formatting of doc generator
      run: npx prettier --check "**/*.{ts,tsx}"
      working-directory: js-pkg/gen-docs/

    - name: Check Formatting of scripts
      run: npx prettier --check "**/*.{ts,tsx}"
      working-directory: scripts/

    - name: Check that workspace package versions match
      run: npx ts-node scripts/set-js-versions.ts
      
