name: Integration Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/integration-tests.yml"
      - "tests/**"
      - "crates/**"
      - "js-pkg/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  integration-test:
    runs-on: ubuntu-latest-16-cores
    container: ghcr.io/drifting-in-space/cicd-runner-base:main

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          crates/target/
          crates/y-sweet-worker/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Test deps
      run: npm ci
      working-directory: tests
    - name: Run integration tests
      run: npm test
      env:
        Y_SWEET_S3_ACCESS_KEY_ID: ${{ secrets.Y_SWEET_S3_ACCESS_KEY_ID }}
        Y_SWEET_S3_SECRET_KEY: ${{ secrets.Y_SWEET_S3_SECRET_KEY }}
        Y_SWEET_S3_REGION: us-east-1
        Y_SWEET_S3_BUCKET_PREFIX: testing
        Y_SWEET_S3_BUCKET_NAME: ysweet-testing-y-sweet-data
      working-directory: tests
      timeout-minutes: 10

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-data
        path: tests/out
