name: Rustfmt

on:
  pull_request:
    branches: [ "*" ]
    paths:
      - "crates/**"

jobs:
  check_format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Check format
        run: cargo fmt -- --check
      - name: Check format
        run: cargo fmt -- --check
        working-directory: ./crates/y-sweet-worker
