name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "crates/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    defaults:
      run:
        working-directory: ./crates

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"

    - name: Run unit tests
      run: cargo test --verbose

